/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/chords/': RouteRecordInfo<'/chords/', '/chords', Record<never, never>, Record<never, never>>,
    '/chords/allChordsAudio': RouteRecordInfo<'/chords/allChordsAudio', '/chords/allChordsAudio', Record<never, never>, Record<never, never>>,
    '/chords/allChordsVisual': RouteRecordInfo<'/chords/allChordsVisual', '/chords/allChordsVisual', Record<never, never>, Record<never, never>>,
    '/chords/basicChordsAudio': RouteRecordInfo<'/chords/basicChordsAudio', '/chords/basicChordsAudio', Record<never, never>, Record<never, never>>,
    '/chords/basicChordsAudiotheoretical': RouteRecordInfo<'/chords/basicChordsAudiotheoretical', '/chords/basicChordsAudiotheoretical', Record<never, never>, Record<never, never>>,
    '/chords/basicChordsVisual': RouteRecordInfo<'/chords/basicChordsVisual', '/chords/basicChordsVisual', Record<never, never>, Record<never, never>>,
    '/chords/basicDiminishedChordsAudio': RouteRecordInfo<'/chords/basicDiminishedChordsAudio', '/chords/basicDiminishedChordsAudio', Record<never, never>, Record<never, never>>,
    '/chords/basicDiminishedChordsVisual': RouteRecordInfo<'/chords/basicDiminishedChordsVisual', '/chords/basicDiminishedChordsVisual', Record<never, never>, Record<never, never>>,
    '/chords/basicMajorChordsVisual': RouteRecordInfo<'/chords/basicMajorChordsVisual', '/chords/basicMajorChordsVisual', Record<never, never>, Record<never, never>>,
    '/chords/basicMinorChordsVisual': RouteRecordInfo<'/chords/basicMinorChordsVisual', '/chords/basicMinorChordsVisual', Record<never, never>, Record<never, never>>,
    '/chords/basicSeventhChordsVisual': RouteRecordInfo<'/chords/basicSeventhChordsVisual', '/chords/basicSeventhChordsVisual', Record<never, never>, Record<never, never>>,
    '/chords/seventhChordsAudio': RouteRecordInfo<'/chords/seventhChordsAudio', '/chords/seventhChordsAudio', Record<never, never>, Record<never, never>>,
    '/chords/testAudio1': RouteRecordInfo<'/chords/testAudio1', '/chords/testAudio1', Record<never, never>, Record<never, never>>,
    '/chords/testGraphic1': RouteRecordInfo<'/chords/testGraphic1', '/chords/testGraphic1', Record<never, never>, Record<never, never>>,
    '/Fretboard': RouteRecordInfo<'/Fretboard', '/Fretboard', Record<never, never>, Record<never, never>>,
    '/fretboardOld': RouteRecordInfo<'/fretboardOld', '/fretboardOld', Record<never, never>, Record<never, never>>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/chordNotes': RouteRecordInfo<'/notes/chordNotes', '/notes/chordNotes', Record<never, never>, Record<never, never>>,
    '/notes/intervalRecognizerAudio': RouteRecordInfo<'/notes/intervalRecognizerAudio', '/notes/intervalRecognizerAudio', Record<never, never>, Record<never, never>>,
    '/notes/missingChordNotes': RouteRecordInfo<'/notes/missingChordNotes', '/notes/missingChordNotes', Record<never, never>, Record<never, never>>,
    '/notes/notesAudio': RouteRecordInfo<'/notes/notesAudio', '/notes/notesAudio', Record<never, never>, Record<never, never>>,
    '/notes/notesAudioHard': RouteRecordInfo<'/notes/notesAudioHard', '/notes/notesAudioHard', Record<never, never>, Record<never, never>>,
    '/notes/openStringAudio': RouteRecordInfo<'/notes/openStringAudio', '/notes/openStringAudio', Record<never, never>, Record<never, never>>,
    '/notes/openStringTest': RouteRecordInfo<'/notes/openStringTest', '/notes/openStringTest', Record<never, never>, Record<never, never>>,
    '/notes/stringNoteFinder': RouteRecordInfo<'/notes/stringNoteFinder', '/notes/stringNoteFinder', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/scales/': RouteRecordInfo<'/scales/', '/scales', Record<never, never>, Record<never, never>>,
    '/scales/chordFormula': RouteRecordInfo<'/scales/chordFormula', '/scales/chordFormula', Record<never, never>, Record<never, never>>,
    '/scales/chordNameToFormula': RouteRecordInfo<'/scales/chordNameToFormula', '/scales/chordNameToFormula', Record<never, never>, Record<never, never>>,
    '/scales/intervalWithinScale': RouteRecordInfo<'/scales/intervalWithinScale', '/scales/intervalWithinScale', Record<never, never>, Record<never, never>>,
    '/scales/intervalWithinScaleAll': RouteRecordInfo<'/scales/intervalWithinScaleAll', '/scales/intervalWithinScaleAll', Record<never, never>, Record<never, never>>,
    '/scales/missingNote': RouteRecordInfo<'/scales/missingNote', '/scales/missingNote', Record<never, never>, Record<never, never>>,
    '/scales/nameTheScale': RouteRecordInfo<'/scales/nameTheScale', '/scales/nameTheScale', Record<never, never>, Record<never, never>>,
    '/scales/scaleInterval': RouteRecordInfo<'/scales/scaleInterval', '/scales/scaleInterval', Record<never, never>, Record<never, never>>,
    '/scales/scaleVisualizer': RouteRecordInfo<'/scales/scaleVisualizer', '/scales/scaleVisualizer', Record<never, never>, Record<never, never>>,
    '/trueOrFalse': RouteRecordInfo<'/trueOrFalse', '/trueOrFalse', Record<never, never>, Record<never, never>>,
  }
}
